### ISSUE TITLE
Using analogs pins 3 4 and 10 on micro:bit

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#611] opened 2016-10-28 11:42 UTC
microbit.org-ticket: 177

A customer has requested help with using the analog inputs on micro:bit pins 3,4 and 10. These currently cause a conflict with the display driver, and return spurious values and cause interactions with the screen (even if the screen is black, the display driver is controlling the row's and using analog/digital switching in the multiplex to do the light sensing feature).

Could we add a block to the 'pins' palette to say 'display disable' and 'display enable' (or even display enable(bool)) depending on your preference for consistency with palette names and use.

The service to wrap is uBit.display.enable - we could surface a pxt package that does this, but it is a common feature that users always want to use more analogs, and they are happy to sacrafice the display in return for more analog inputs (e.g. in a datalogging setup). At present there seems no way to call the uBit.display.enable from any of the shims I can find in all the .ts files.

You can find a full list of 'how to uncouple default functionality from pins' in this datasheet along with the DAL service that needs to be called. I think it is just the analog pins we need access to, so all we need to surface is a display_on and display_off feature

http://tech.microbit.org/hardware/edgeconnector_ds/

**Comment by pelikhan** [comment] 2016-10-28 13:43
Sounds reasonable. Would it make sense to automatically shut down the screen when these pin are used?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment] 2016-10-28 14:08
PR https://github.com/Microsoft/pxt-microbit/pull/294

**Comment by whaleygeek** [comment] 2016-10-28 15:08
Hi @pelikhan I'm not completely sure of the workflow that would be right for this, now you mention it.

I can see it seeming like a good idea to make it automatic, but there might be some use cases where this gets confusing to users. So we might just have to think through the options a bit. Also turning off the display in the DAL stops the light sensing feature (apparently), so we're already getting into a few different combinations of options.

Shall I chat this over with Jonny and we'll try and come up with a more well-rounded suggestion for how this might surface in the editor for you you?

My only other thought is, is it easy for you to create a small pxt package for us that adds this functionality, so that we can test that the interactions with the analogs at the hardware level are as we expect, before we commit any real time to surfacing this for real? It would also give users a way to use those analogs in the short term until we work out the best way to surface this feature to them, and feedback from real users with this temporary solution might shape our thinking about a more permanent solution? It seems like a nice use of the packaging feature, to try out ideas.

**Comment by pelikhan** [comment] 2016-10-28 15:18
Thinking of it, this is an advanced option. Users who will be able to access those pins are already more advanced and should turn off the display themselfves.

**Comment by pelikhan** [comment] 2016-10-28 18:23
PR in /beta. Please reopen if needed.

**Comment by whaleygeek** [comment] 2016-11-01 14:54
Hi @pelikhan could you send me a link to the /beta PR that I should monitor, I'm not sure where to find this, thanks.

**Comment by jaustin** [comment] 2016-12-05 16:32
Looking at the beta today I can't see this - @pelikhan can you please let me know where it lives?

**Comment by whaleygeek** [comment] 2016-12-12 07:51
Has this been deployed yet?

**Comment by DavidWhaleIET** [comment] 2017-01-10 14:33
Has this been deployed yet @jaustin ? How do I check myself if this has been deployed?

**Comment by pelikhan** [comment] 2017-01-10 14:51
Not implemented yet.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaustin** [comment] 2017-01-23 23:27
@pelikhan not *implemented* or not pushed? If not implemented can we re-open this bug please - it's a limitation to people making advanced accessories. If it's implemented (and it looks from the PR above that it is) - what's holding back the merge and subsequent release?

**Comment by pelikhan** [comment] 2017-01-24 01:34
This is a breaking API change that requires special patching of blockly source code. Did this get closed? The fix is not implemented yet.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaustin** [comment] 2017-01-24 01:51
Yep - you closed it!

pelikhan commented on 28 Oct 2016
> PR in /beta. Please reopen if needed.
@pelikhan pelikhan closed this on 28 Oct 2016

So, I'd say needed - can you please re-open :)

**Comment by jaustin** [comment] 2017-02-07 16:37
Let's have 4 enums going forward:
one each of:
- Digitial in
- Digital out
- Analog in
- Analog out

We can then look at the object orientation in the future.

**Comment by pelikhan** [comment] 2017-02-08 23:36
After investigating the feasibility of swapping in 4 new pin sets, we have decided that it is too risky to implement. Instead, we are extending the AnalogPin enum to all DigitalPin.

* this is suboptimal in blocks but it is mitigated by the fact that this is a advanced feature requering a shield to access those pins.
* calling an analog function on an unsupported pin is no-op.
* the list is annontated with "(write only)" to hint only
![image](https://cloud.githubusercontent.com/assets/4175913/22762434/25a9bb9e-ee14-11e6-95cd-ad2f285fa164.png)

**Comment by pelikhan** [comment] 2017-02-08 23:44
In v0.9.1

**Closed by pelikhan** 2017-02-08 23:44 UTC
Labels: enhancement, Microbit Foundation, P1

**Comment by d-f-booth** [comment] 2017-02-11 16:53
Using the Tx hex and RX files zipped below I have tested pins P0, P1, P2 and P10 and got a good PWM signals P3 and P4 gave PWM outputs but in the case of P4 LEDs at (0, 2) and (4 ,4) were lit.  Pin P3 gave a good PWM signal with a couple extra LEDs lit.

I tested the pins P8, P12 and P16 which are of particular interest to me and they just gave a zero volts output.  Pin P5 gave a logical 1 output.

In all cases I took the PXT script that worked for P0 and P1 and only changed the selection of the pin in the second analog write block then recompiled and flashed to the receiver Rx without turning off the TX or removing power from the RX micro:bit

I made no attempt to suppress other activities on the pins concerned, mainly because I do not know how to do that. 
Pins were monitored by an oscilloscope.

The Rx file below is set up to drive pin P8.  Change the P8 to P1 to see the difference.

David Booth

[microbit-Radio-Tx-P1M1.zip](https://github.com/Microsoft/pxt/files/768629/microbit-Radio-Tx-P1M1.zip)
[microbit-Radio-Rx-for-P0-P8 (2).zip](https://github.com/Microsoft/pxt/files/768630/microbit-Radio-Rx-for-P0-P8.2.zip)

**Comment by whaleygeek** [comment] 2017-02-11 17:07
@abchatra Could you re-open this ticket please, my users are still reporting problems with this. Thanks

**Comment by whaleygeek** [comment] 2017-02-11 17:11
@d-f-booth Could you confirm the URL of the editor you used for this? You need to test this against the /beta URL, as the live has not got the fixes on yet. @pelikhan stated v0.9.1 is when the fixes first surfaced. Below are the current snapshot of versions on live and beta:

![screen shot 2017-02-11 at 17 08 31](https://cloud.githubusercontent.com/assets/4086785/22855748/e707f836-f07c-11e6-84de-a974b843cd01.png)

![screen shot 2017-02-11 at 17 08 49](https://cloud.githubusercontent.com/assets/4086785/22855749/eb52d15e-f07c-11e6-8aaa-d0fcc6ac8269.png)

live: 0.7.41
beta: 0.9.4 <- must use beta to get the v0.9.1 fixes done to PWM

**Comment by pelikhan** [comment] 2017-02-11 17:17
PXT pin apis is a very shallow layer on top of the DAL. Most likely those issues are DAL related. I would recommend writing a c++ sample that uses the DAL to see if the issue is with PXT or the DAL.

Make sure you are using PXT.microbit.org/beta

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by whaleygeek** [comment] 2017-02-11 17:37
Thanks. @pelikhan how do I check which version of the DAL is currently used by PXT?

**Comment by pelikhan** [comment] 2017-02-11 17:38
Gearwheel button, about.

**Comment by whaleygeek** [comment] 2017-02-11 17:40
Which one of these numbers is the DAL version?

![screen shot 2017-02-11 at 17 37 34](https://cloud.githubusercontent.com/assets/4086785/22855986/17338332-f081-11e6-89cf-378d7b1b7695.png)

Or can I get it from any of these files...

![screen shot 2017-02-11 at 17 38 31](https://cloud.githubusercontent.com/assets/4086785/22855987/1d3a1a2a-f081-11e6-9278-fd9dcdc39553.png)

**Comment by whaleygeek** [comment] 2017-02-11 17:49
![screen shot 2017-02-11 at 17 48 06](https://cloud.githubusercontent.com/assets/4086785/22856069/6133f844-f082-11e6-90de-be6e517d545a.png)

Ok, so I didn't realise there were two repos, and you ask us to log issues against the core pxt, but make changes against the microbit one (pulling in core code from the core repo as needed). Makes sense now thanks.

**Comment by whaleygeek** [comment] 2017-02-11 18:01
@jaustin @pelikhan Discussion for another day: We need some tooling here so that I can easily generate a descriptive release note for each release, so I know what's in, what has changed, what's still a bug.

0. given a .hex file from a user, drag it into some tool and it works out what version of PXT generated it by looking at the metadata, and prints that. 
1. or, for current or any URL permalinked release: Look at gearwheel about from PXT, get two version numbers
2. follow the pxt core version number to github pxt core, get the release tag
3. follow the release tag to get the commits against that release
4. (how do I find out which issue numbers were fixed in that release?)
5. using pxt.microbit version number from about box, hop to pxt microbit github and find the release tag
6. get a list of commits against that tag
7. (how do I find out which issue numbers were fixed in that release?)
8. given that pxt-microbit release tag, look at the pxttarget.json and manually grab the DAL github version and URL
9. hop over to lancaster github, find that release tag
10. get commits against that release tag
11. (how do I find out which issues were fixed as part of that release?)

I now presumably have a list of all changes that were done in that one PXT release, right down to the DAL, and can then follow through them to work out if the problem a customer is reporting is (a) a known problem (b) a fixed problem (c) an outstanding problem.

To me, this then looks like a release note. Auto generated from the data we already collect in the various github repos.

**Comment by pelikhan** [comment] 2017-02-11 18:57
I can surface the dal version in the about page which will save you a hop. Again, once we go in RC, things will be slower.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by OwenBrotherwood** [comment] 2017-02-12 06:47
https://github.com/lancaster-university/microbit-dal/issues/266

**Comment by pelikhan** [comment] 2017-02-15 16:02
In beta, the about page also displays/links the DAL version

**Comment by whaleygeek** [comment] 2017-02-15 17:00
You're right, it does! Excellent, thanks! That will save me one hop!

![screen shot 2017-02-15 at 17 00 15](https://cloud.githubusercontent.com/assets/4086785/22985433/4e22d1c8-f3a0-11e6-9d5a-0bd4b5a25e6a.png)

**Comment by luniki** [comment] 2017-02-15 18:25
I am interested in P8, 12 and 16 too.

In https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitIO.cpp all of them are defined as:

    P8 (ID_P8, MICROBIT_PIN_P8, PIN_CAPABILITY_DIGITAL),        //PIN 18
    P12(ID_P12,MICROBIT_PIN_P12,PIN_CAPABILITY_DIGITAL), //PIN 20
    ...
    P16(ID_P16,MICROBIT_PIN_P16,PIN_CAPABILITY_DIGITAL), 

In https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitPin.cpp the function setAnalogValue contains:

    int MicroBitPin::setAnalogValue(int value)
    {
        //check if this pin has an analogue mode...
        if(!(PIN_CAPABILITY_ANALOG & capability))
            return MICROBIT_NOT_SUPPORTED;
    ...

So if P8, 12 and 16 would be defined as PIN_CAPABILITY_AD could they be used for PWM?

**Comment by nevilh** [comment] 2017-02-27 09:43
Hi Peli,
FYI I've just tried PWM with P14 and I can't get it to work. (The same code works fine using P2)
I've read some of this thread and it sounds like some fixes went in 11.28. I am using 11.39 so I should have those fixes. Getting PWM working with P14 would be useful as it is one of the pins my "zbit:shaker" motor can attach to.
Cheers,
Nevil

**Comment by pelikhan** [comment] 2017-02-27 14:38
The capabailoty of the pins need to be update in the DAL.

**Comment by DavidWhaleMEF** [comment] 2017-02-27 17:59
For reference, the activity to make that happen is here, waiting testing:

https://github.com/lancaster-university/microbit-dal/issues/115
