### ISSUE TITLE
The block "wait" under "CONTROL" doesn't work normally

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2228] opened 2017-06-06 08:58 UTC
Repro steps:
• Navigate to https://makecode.adafruit.com/
• drag the block "show ring" under "LIGHT" and put it under the loop "forever"
• drag the block "wait" under "CONTROL" and put it under the "show ring"

Expected result:
 It should display normally
Actual result:
 It prompts there is program error "Program Error: sim error: noresume"
![control](https://cloud.githubusercontent.com/assets/11880996/26819910/897e81ce-4ad3-11e7-85a5-68ec6bdf3972.gif)

**Comment by tballmsft** [comment] 2017-06-08 00:54
Only need this:
```
control.waitMicros(4) 
```

**Comment by tballmsft** [comment] 2017-06-08 00:57
The problem is that waitMicros isn't annotated async but calls thread.pause:
```
    export function waitMicros(micros: number) {
        thread.pause(micros / 1000); // it prempts not much we can do here.
    }
```

**Comment by tballmsft** [comment] 2017-06-08 01:19
@pelikhan - what's your recommendation. Should we make the JS wait async or replace the implementation with a true blocking implementation?  Can we make the JS wait async without also doing so for the C++ version?

**Comment by tballmsft** [comment] 2017-06-09 16:53
Fixed by making "async": https://github.com/Microsoft/pxt-common-packages/commit/02872e2f38fff3db1ac2d0263bce65922369e596

**Closed by tballmsft** 2017-06-09 16:53 UTC
Labels: bug, cti team, P2, simulator
