### ISSUE TITLE
Useless variable can't be deleted unless refresh the page

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2367] opened 2017-06-28 07:22 UTC
**Repro steps:**
• Navigate to https://makecode.microbit.org/ 
• Drag blocks as below picture
• Create a new variable named "test" and try to delete it

**Expected result:**
 Variable "test" could be deleted
**Actual result:**
 Variable "test" can't be deleted unless refresh the page
![1](https://user-images.githubusercontent.com/23466737/27624854-0c88382e-5c15-11e7-9559-67512d4ca142.gif)

**Comment by abchatra** [comment] 2017-07-03 20:26
Won't fix. This is by design in blockly.

**Closed by abchatra** 2017-07-03 20:26 UTC
