### ISSUE TITLE
"Variables" has no string initialisation set item to string

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt#916] opened 2016-12-10 23:31 UTC
Given in Javascript:
let me = "owen"
The Block representation is two blocks, a set item me and a string item "owen"
This easy block start is not available in "Variables" whereas the following is
let nr = 1

**Comment by abchatra** [comment] 2016-12-11 18:18
@OwenBrotherwood Can you provide screenshots? I don't know what you mean by easy block start.

**Comment by OwenBrotherwood** [comment] 2016-12-11 18:23
I am unsure as to easily initialise a string value.
There seems only an initialisation of a nr.

![image](https://cloud.githubusercontent.com/assets/866122/21082201/23ade150-bfd7-11e6-9fb1-f3d4c24e554c.png)

**Comment by abchatra** [comment] 2016-12-11 18:29
This is duplicate of https://github.com/Microsoft/pxt/issues/531

**Closed by abchatra** 2016-12-11 18:29 UTC
Labels: Needs Additional Information

**Comment by OwenBrotherwood** [comment] 2016-12-11 18:31
Sorry, I didn't look so far back
