### ISSUE TITLE
The instruction of item on block "join" is not clear 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#3949] opened 2018-03-06 09:14 UTC
**Repro steps:**
• Navigate to https://makecode.microbit.org/beta
• Drag blocks as below picture
• Click "setting" on block "join" and move cursor mouse on "item"

**Expect result:**
The instruction of item should be more clear
**Actual result:**
The instruction of item is not clear on block "join"
![compare](https://user-images.githubusercontent.com/23466737/37023577-4ae28df8-211e-11e8-9796-677e57ffc2d7.png)

**Comment by samelhusseini** [comment] 2018-04-13 08:11
Dupe of https://github.com/Microsoft/pxt-microbit/issues/737

**Closed by samelhusseini** 2018-04-13 08:11 UTC
