### ISSUE TITLE
set brightness does not work in on screen simulator

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1742] opened 2017-03-24 12:53 UTC
microbit.org-ticket: 1430

The set brightness doesn't seem to work in the simulator?

[microbit-brightness.hex.zip](https://github.com/Microsoft/pxt/files/867864/microbit-brightness.hex.zip)

**Comment by DavidWhaleMEF** [comment] 2017-03-24 12:54
pxt.microbit.org version: 0.9.55
Microsoft MakeCode version: 0.12.1
C++ runtime version: v2.0.0-rc8

**Comment by pelikhan** [comment] 2017-03-24 14:14
Computer screens are not as bright as LEDs. Change the brightness makes the LEDs unviewable so we decided to ignore that value.

**Comment by jaustin** [comment] 2017-07-10 21:07
This is a fairly major confusion and makes it hard for people to use the "set brightness" block and get an idea of what they're doing. 

It's also bad from a 'kid' point of view because they can't tell whether the simulator isn't working, or they've got their code wrong. We don't even warn that the simulator won't show it.

Finally, it also makes it impossible to faithfully reproduce the micro:bit "Out of Box Experience" in the MakeCode simulator....

The simulator at create.withcode.uk supports this with red->black gradients and it looks pretty good:

![image](https://user-images.githubusercontent.com/147113/28039925-e13e1714-65bb-11e7-8927-92dd1e7f494a.png)

Can you please reconsider this?

**Comment by jaustin** [comment] 2017-07-10 21:11
@abchatra (mentioning because I'm not sure if you'd ever see comments on closed bugs) - can we consider reopening this please?

**Comment by jaustin** [comment] 2017-07-11 16:40
https://github.com/Microsoft/pxt/issues/1069 Can this perhaps be tackled at the same time - looks like you've sorted out how to do a nice glow now in Circuit Playground and wonder about using the same technique on the MB LEDs at the same time as implementing fade?

**Comment by jaustin** [comment] 2017-07-12 11:23
Also note that the 'item set brightness' block from the "game" module works as expected (IE does dim the LED), but needs a different gamma curve to be sure that the micro:bit numbers map well to some displays.

https://github.com/Microsoft/pxt/issues/2439

**Comment by microsoftsam** [comment] 2017-07-28 18:42
@jaustin thoughts on this glow? 

https://jsfiddle.net/hmbg4t1h/

**Comment by microsoftsam** [comment] 2017-08-11 20:51
Fixed in /beta

**Closed by microsoftsam** 2017-08-11 20:51 UTC
Labels: bug, help wanted, P2
