### ISSUE TITLE
Some program screenshots don't work

### ISSUE THREAD

**Issue by HyperDuino** [Microsoft/pxt#2427] opened 2017-07-10 19:50 UTC
For this shared program:
https://makecode.microbit.org/33215-57699-87157-67857

If I click "Edit" and open a copy, and then do a right-click for the contextual menu and choose "download screenshot"s, I get an error from Chrome browser (Version 59.0.3071.115 ) + Mac OS X 10.11.6 that says "Failed - Network error".

Other block programs successfully download screenshots.

The hex code opened as a block program from Kitronics has the same problem:

Hex/Block Code is on this page:
https://www.kitronik.co.uk/blog/part-6-coding-with-the-pxt-editor

With this link:
https://www.kitronik.co.uk/zip/microbit-Robot-Wars-Buggy-Code.zip (252,000 bytes)
Unzipped:  605,577 bytes

When imported into https://makecode.microbit.org/ and right-click to download screenshot, the "Failed - Network error" also occurs.

**Comment by abchatra** [comment] 2017-07-10 20:49
Duplicate of https://github.com/Microsoft/pxt/issues/2330

**Closed by abchatra** 2017-07-10 20:49 UTC
