### ISSUE TITLE
Minor overflow issue in firefox share page

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#1619] opened 2017-03-13 23:12 UTC
![share_page_firefox](https://cloud.githubusercontent.com/assets/13754588/23879018/d8d55aea-0807-11e7-954c-0e9a30b07e37.PNG)

**Comment by microsoftsam** [comment] 2017-03-14 05:42
Dupe of #1625

**Comment by microsoftsam** [comment] 2017-03-14 05:42
Repro's on all sandbox views, not just firefox.

**Closed by microsoftsam** 2017-03-14 05:42 UTC
Labels: browser compat, embed, P3
