### ISSUE TITLE
Round trip issue with repeat

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#129] opened 2016-07-20 11:45 UTC
The following code fails to convert to blocks 

``` typescript
for (let i = 0; i < 4; i++) {
    basic.showNumber(i)
}
```

This can occur if you drag in a `repeat` loop, which doesn't have an iterator variable in blocks, go to the code, and add something to the loop body that uses that variable.

**Comment by pelikhan** [comment] 2016-08-03 23:34
Maybe we should drop the "repeat" block.

**Comment by mmoskal** [comment] 2016-09-03 09:09
I don't think dropping the block would help - the issue is that we cannot handle `<` in loop condition in decompilation

**Comment by thomasdenney** [comment] 2016-09-07 07:38
Related to https://github.com/Microsoft/pxt/issues/229

**Comment by riknoll** [comment] 2016-10-11 20:37
This no longer fails to decompile or at least it won't once the roundtrip is removed. However, I'm going to leave this open because right now we decompile all for-loops into for-loop blocks (never repeat blocks). In order to decompile a repeat block we need to be sure that the variable in the initializer is never referenced within the body of the loop.

**Comment by abchatra** [comment] 2016-11-02 22:39
Decompilation works now, even though you may not get the exact repeat block. I am closing this, as this will require some static analysis. Also switching back to different blocks may be ok for users who want to try typescript.

**Closed by abchatra** 2016-11-02 22:39 UTC
Labels: Blocks <==> TypeScript, bug, JavaScript backend, P2
