### ISSUE TITLE
After added some packages, it doesn’t display these package on editor.

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#2194] opened 2017-05-31 09:25 UTC
**Repro step:**
- Navigate to https://makecode.adafruit.com/
- Click “setting” and choose “Add package”
- Add any packages such as “neoanim”

**Expected result:**
Added package, It should display it on editor after auto refresh.

**Actual result:**
It doesn’t display on editor. But it display on EXPLORER under JavaScript
![package](https://cloud.githubusercontent.com/assets/17866936/26625214/01da7afe-4626-11e7-8384-426adcef9493.PNG)

**Comment by pelikhan** [comment] 2017-05-31 13:34
This package does not expose blocks. By design.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment] 2017-06-02 23:48
This is by design, Won't fix

**Closed by abchatra** 2017-06-02 23:48 UTC
Labels: cti team
