### ISSUE TITLE
Circular references lead to memory leaks

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#139] opened 2016-07-21 14:02 UTC
The following program leads to an out of memory error (":( 020" displays on the LEDs).

``` typescript
class A {
    child: B
}
class B {
    parent: A
}

while (true) {
    let a = new A()
    let b = new B()
    a.child = b
    b.parent = a
}
```

The only solutions I know of to resolving this are explicitly marking references as weak or having a garbage collector run occasionally to detect cycles.

**Comment by thomasdenney** [comment] 2016-07-21 14:15
Whilst it didn't crash the browser, I found that memory usage (in Chrome) for the app came to about 1.5G before the page became unresponsive.

**Comment by mmoskal** [comment] 2016-07-21 17:04
This will only happen if we run with the reference counting on (which is to say for all hardware targets; it won't happen for bot framework etc). This is by design, but should be **documented**.

**Comment by abchatra** [comment] 2016-09-19 22:57
Peli & Abhijith: Ideal is simulator detect the memory leak and warn the user.

**Comment by mmoskal** [comment] 2016-09-28 11:17
We have a way of dumping all live pointers. It would be easy to count the number of live objects and stop the program if they exceed say 2000 (which would crash the real microbit). I can add that, but still needs to be documented.

**Comment by tballmsft** [comment] 2017-04-01 19:16
Closing. By design.

**Closed by tballmsft** 2017-04-01 19:16 UTC
Labels: enhancement, JavaScript backend, simulator
