### ISSUE TITLE
collapse simulator in timing gates project

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt#2269] opened 2017-06-12 21:15 UTC
It appears that the simulator is not working with the finished script from timing gates:

```
let t0 = 0;
let t1 = 0;
basic.showLeds(`
        . . . . .
        . . . . .
        . . # . .
        . . . . .
        . . . . .
        `)
input.onPinPressed(TouchPin.P0, () => {
    t0 = control.eventTimestamp();
    basic.showLeds(`
        # . . . .
        # . . . .
        # . . . .
        # . . . .
        # . . . .
        `)
})
input.onPinPressed(TouchPin.P1, () => {
    t1 = control.eventTimestamp();
    basic.showLeds(`
        # . . . #
        # . . . #
        # . . . #
        # . . . #
        # . . . #
        `)
    let d = t1 - t0
    basic.showNumber(d)
})
```
 
after testing the simulator with the timing gates project, here is the program error message when pressing P0:

```
program error: pxsim.control.eventTimestqmp is not a function.
```

can you collapse the simulator when using control.eventTimestamp?

**Comment by microsoftsam** [comment] 2017-06-12 22:00
the fix here is to implement the control.eventTimestamp method in sim.

**Comment by mebrauns** [comment] 2017-06-13 00:15
it would be great to have the simulator removed when using control.eventTimestamp. 

or maybe the team can implement the control.eventTimestamp in simulator.

**Comment by abchatra** [comment] 2017-06-13 20:15
This is dupe of https://github.com/Microsoft/pxt/issues/395

**Closed by abchatra** 2017-06-13 20:15 UTC
Labels: bug, P2, simulator

**Comment by caitlin-hennessy** [comment] 2017-08-02 17:50
Resolved by https://github.com/Microsoft/pxt/pull/2615 and https://github.com/Microsoft/pxt-microbit/pull/484.
