### ISSUE TITLE
When switch the language to "Sri Lanka" and "Japanese", "on start" and "forever" show abnormally

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#2016] opened 2017-05-02 08:34 UTC
**Repro steps:**
• Navigate to https://pxt.microbit.org/beta 
• Click "More..." and choose Language
• Choose "Sri Lanka" or "Japanese"

**Results:**
 **"Japanese"** :only repro on IE
![11](https://cloud.githubusercontent.com/assets/23497626/25609997/0fb0badc-2f54-11e7-988d-e74c77ea0a4e.PNG)
**"Sri Lanka"** : repro on all browsers
![23](https://cloud.githubusercontent.com/assets/23497626/25610749/0221ec4e-2f57-11e7-8eb5-55afac9fe9fb.png)

**Comment by pelikhan** [comment] 2017-05-02 12:57
There is a font size computation in IE/Edge for blocks. Dup.

**Comment by abchatra** [comment] 2017-05-03 00:02
Duplicate of https://github.com/Microsoft/pxt/issues/1521

**Closed by abchatra** 2017-05-03 00:02 UTC
Labels: bug, cti team, localization, P2
