### ISSUE TITLE
Blocks spawn inside toolbox when opening project

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt#681] opened 2016-11-04 19:17 UTC
Blocks spawn inside the toolbox when you load a project, then leap out once the toolbox loads. It looks pretty bad.

**Comment by abchatra** [comment] 2016-11-04 21:21
I believe @microsoftsam has fix for this

**Comment by microsoftsam** [comment] 2016-11-04 21:54
Fixed by #691 
If you're interested in the root cause: 
This started happening when we moved our entire toolbox to load when we loaded blockly. So when blockly first loaded, it had no toolbox. The coordinates for the Blocks are placed under the assumption that no toolbox exists. When we add the toolbox, it is then adjusted.

**Comment by abchatra** [comment] 2016-11-07 01:18
Fixed

**Closed by abchatra** 2016-11-07 01:18 UTC
Labels: Blocks editor, bug, P1, Web App
