### ISSUE TITLE
After released the button "P0", the selected box of Slow-Mo doesn't locate to "basic.showIcon(IconNames.Yes)".

### ISSUE THREAD

**Issue by Emma-sunny** [Microsoft/pxt#3599] opened 2017-12-08 03:26 UTC
**Repro step:**
- Navigate to [https://makecode.microbit.org/beta](url)
- switch "BLocks" to "_{}JavaScript_" and copy the following code to content panel:
   "
    _input.onPinReleased(TouchPin.P0, () => {    basic.showIcon(IconNames.Yes) })
    input.onPinPressed(TouchPin.P0, () => {    basic.showNumber(1)})_   
   "
- Enable "_Slow-Mo_"

**Expected Result:**
If released the button "_P0_", the event "_input.onPinReleased()_" could be triggered. So the selected box of Slow-Mo should locate to "_basic.showIcon(IconNames.Yes)_".

**Actual Result:**
When released the button "_P0_", the slow-mo doesn't locate to "_basic.showIcon(IconNames.Yes)_".Detail as follows:
![slow-moissue](https://user-images.githubusercontent.com/17866936/33749547-4188b408-dc09-11e7-863f-55f3b5d0d62e.gif)

**Comment by abchatra** [comment] 2018-01-02 22:43
This is a duplicate of https://github.com/Microsoft/pxt/issues/2495

**Closed by abchatra** 2018-01-02 22:43 UTC
Labels: bug, P2, simulator
