### ISSUE TITLE
File system feedback from customer

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1962] opened 2017-04-24 23:24 UTC
microbit.org-ticket: 1421

I couldn't make sense of the discussions in the microbit or Microsoft 
forums that you pointed me to. Nor can I find any documentation on the 
PXT File blocks in https://pxt.microbit.org/reference/. (And right 
click on a File block has its 'Help' option greyed out). So that code 
is scarcely even in Beta, it would seem.

I assume, therefore, that collecting data on the microbit over a 
period for subsequent retrieval is not supported by PXT for the time 
being.

I now know that there's a rudimentary file system for microPython, but 
that's a step too far for my Year 5 Code Clubbers who have experienced 
only graphical block coding.

**Comment by tballmsft** [comment] 2017-04-25 16:48
@whaleygeek - we could use some help here.

**Comment by abchatra** [comment] 2017-04-25 17:21
@whaleygeek  File system is not ready until we can make is visible over USB. What is the action on us here?

**Comment by pelikhan** [comment] 2017-04-25 17:58
* in beta, the file system package is clearly marked as "beta" in the UI
* we should automatically route "help" requests from packages loaded from github to the package docs page, eg. https://pxt.microbit.org/pkg/microsoft/pxt-filesystem

**Comment by pelikhan** [comment] 2017-04-25 18:30
Shipping an updated DAPLink bootloader that supports MSC and avoid erasing bonding information.

**Comment by whaleygeek** [comment] 2017-04-25 18:42
Thanks guys, terribly sorry I got ahead of myself with cut and paste and forgot to add the 'valuable info' round the outside :(

But you've answered the core question which is, its not quite ready yet for consumption by users. Thanks for the extra info.

@abchatra Action here really is for us all to make sure that any dependent activities (e.g. DAL and daplink work) required to surface this feature, are logged as tickets so that we (me and others) can get all the various moving parts for this feature on the radar. I suspect if they dependent work is not logged as tickets, it will get forgotten or not receive appropriate priority.

We're seeing a lot of interest in the PXT file system from the user base, as data logging is a big thing in schools for science experiments. If users are able to stumble on beta functionality that has not completed testing, we're always going to get tickets logged querying it's status or saying 'it doesn't work' unfortunately.

I'm happy to log github tickets with microbit-dal and daplink repos - but if you are aware of any existing related tickets, or if you need me to log tickets to make sure dependent work is on the radar, here is a good place to link them I think. Thanks.

@tballmsft Regarding docs - more than willing to help here, what can I do to be of assistance? Is this docs of required features, or docs of how to use?

@pelikhan I'll have a look through microbit-dal, although I suspect some of that work on the daplink bootloader is off on a branch somewhere and we need to locate it and link to it.

**Comment by whaleygeek** [comment] 2017-04-25 18:46
FYI, I'm going back to the customer to say that the file system is a work in progress.

If there are other items that are work in progress but in public view in some way, let me have a list of those items and I'll write a k-base article on our support site listing their status. That way, users can self-discover items that are work in progress and I can link through as part of standard responses. We can then review the list from time to time to make sure it is up to date.

Also, unfortunately, there might be some misconceptions into expectations of beta (some users would consider alpha as something that is very early, buggy, at the early ideas testing stage, and beta as something that is almost ready).

Although, I know we are using the 'release candidate' term a lot these days.

Do we need to work up together some terminology (alpha, beta, release candidate, released) and set users's expectations of what each status means perhaps? Again, I could document this on our support k-base and link through users to this if they query the status of something that is in beta.

Thanks!

**Comment by tballmsft** [comment] 2017-04-25 19:49
@whaleygeek - it would be great if you could help us on 
* Nor can I find any documentation on the PXT File blocks in https://pxt.microbit.org/reference/.

**Comment by whaleygeek** [comment] 2017-04-25 20:14
Ok sure. I'm engaging with a couple of users at the moment to find out their common use cases. I am out of action for a couple of days, but I'll pick this up in my voluntary time over the weekend and see if we can push it forward a notch or two.

Great to be working with you again @tballmsft

**Comment by pelikhan** [comment] 2017-04-26 06:22
This PR ( https://github.com/Microsoft/pxt/pull/1979 ) should fix the issue that people don't find the docs of packages. It enables the block help to route to the package online web page.

**Comment by tballmsft** [comment] 2017-04-27 00:06
Thanks, @pelikhan. Are you happy with the state of the file system docs?

**Comment by pelikhan** [comment] 2017-04-27 00:18
I think the issue is that they were not accessible.

**Comment by abchatra** [comment] 2017-05-03 21:47
Yes issue is the files are not accessible. This is an issue not on MakeCode. As Peli pointed out
"Shipping an updated DAPLink bootloader that supports MSC and avoid erasing bonding information."

I am closing the issue on MakeCode.

**Comment by abchatra** [comment] 2017-05-03 22:13
After talking to Peli there are more issues on our side too. I am going to keep this issue open.

**Comment by pelikhan** [comment] 2017-05-30 06:04
microbit v0.12.22 has the FS fixed in the microbit-dal v2.0.0-rc11

**Comment by pelikhan** [comment] 2017-09-12 18:03
Closing this issue as it requires an update of DAPLink on the Foundation side to make the file system truly usable by kids.

**Closed by pelikhan** 2017-09-12 18:03 UTC
Labels: bug, Microbit Foundation, P2
