### ISSUE TITLE
downcasts (and other type unsafe idioms)

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#459] opened 2016-10-10 17:18 UTC
We need to have a policy for what to do with potentially unsafe casts, such as a downcast. Currently, we allow downcasts and don't have a runtime check.   We could disallow potentially unsafe casts as a start.

**Comment by abchatra** [comment] 2016-10-26 01:39
Duplicate of https://github.com/Microsoft/pxt/issues/387

**Closed by abchatra** 2016-10-26 01:39 UTC
Labels: bug, Type Checker
