### ISSUE TITLE
Not possible to access some of the palette on iOS

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1909] opened 2017-04-16 20:21 UTC
microbit.org-ticket: 1251

Using the new PXT editor, which I assume is the recommended editor to use in conjunction with the iPhone/iPad micro:bit app, it's not possible to scroll the block list in the mobile safari browser, so those block menu items that don't fit on screen can't be used. This is probably an issue with the iOS browser, since I've used other web interfaces that are AJAX based that have panes that can't be scrolled, but it does present a real problem for iPhone users in this case.

![pxt](https://cloud.githubusercontent.com/assets/25079586/25074018/a715744c-22ea-11e7-81c0-8130378b41fa.jpg)

**Comment by tballmsft** [comment] 2017-04-16 23:21
This looks like a duplicate of https://github.com/Microsoft/pxt/issues/1828

**Comment by abchatra** [comment] 2017-04-17 13:54
Yes duplicate of #1828

**Closed by abchatra** 2017-04-17 13:54 UTC
Labels: bug, P1

**Comment by DavidWhaleMEF** [comment] 2017-05-02 22:10
So, 1828 is a P2, and 1909 is a P1??

Does it make sense to close one of these down and work through the issue on a single ticket do you think??

**Comment by abchatra** [comment] 2017-05-02 23:14
Yes please, this issue is already closed from our end.
