### ISSUE TITLE
define your own blocks (feature request)

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt#1506] opened 2017-03-02 20:38 UTC
I think it would be really nice if you could define your own blocks by combining a bunch of blocks together, so that you can reuse that piece of code. In javascript this would then be a function. So it would be really nice if you can also pass arguments into this block/function.

**Comment by abchatra** [comment] 2017-03-02 23:49
Duplicate of https://github.com/Microsoft/pxt/issues/1249

**Closed by abchatra** 2017-03-02 23:49 UTC
