### ISSUE TITLE
javascript error causes page layout problem

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1558] opened 2017-03-07 08:04 UTC
Sometimes when typing in javascript by hand, because the auto code checking is running live, I often see the screen disappear after typing part of a line of code. It turns out this is because an error has popped up (before I have even finished typing the line of code) and that has rendered way off the bottom of the screen, and messes up all the screen layout.

It sometimes does this, and sometimes does not. But because the user code disappears off the bottom of the screen the user has to scroll down a long way to see it, and the first thing you think is that all your  code has suddenly disappeared.

OSX: 1010.5
chrome: 56.0.2924.87 (64-bit)

![screen shot 2017-03-07 at 08 00 47](https://cloud.githubusercontent.com/assets/25079586/23647214/8bd84478-030c-11e7-932a-de383a759b51.png)

**Comment by DavidWhaleMEF** [comment] 2017-03-07 08:08
Also sometimes when backspacing over the javascript code, it looks like the whole code has suddenly disappeared, but it has actually gone to a pane right at the bottom of the page.

![screen shot 2017-03-07 at 08 07 44](https://cloud.githubusercontent.com/assets/25079586/23647340/492c619e-030d-11e7-9dfe-87c57618871b.png)

**Comment by microsoftsam** [comment] 2017-03-08 18:02
Dupe of #1485

**Closed** 2017-03-08 23:32 UTC
Labels: bug, Microbit Foundation, monaco editor, P1
