### ISSUE TITLE
Program error: sim check failed

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1612] opened 2017-03-13 20:07 UTC
I get this error when running a script using radio features between two simulated micro:bits, then the radio received block turns pink and I get a sad face with big eyes on the second simulated micro:bit

![screen shot 2017-03-13 at 20 06 08](https://cloud.githubusercontent.com/assets/25079586/23873058/a6c8b094-0828-11e7-9ea0-519c192ee060.png)

**Comment by DavidWhaleMEF** [comment] 2017-03-13 20:16
This is what the receiving micro:bit then looks like.

![screen shot 2017-03-13 at 20 14 34](https://cloud.githubusercontent.com/assets/25079586/23873378/c177c3fc-0829-11e7-8159-bda0a69d941c.png)

The sending micro:bit sends this:

![screen shot 2017-03-13 at 20 15 31](https://cloud.githubusercontent.com/assets/25079586/23873412/d66b664c-0829-11e7-9ccc-d54cf7ac5bd4.png)

Where my label is set to the string "NA$A" and value is a number variable now holding the value 1.

I can't share my full script with you as it is part of a blind challenge that students must not be able to see the script for, otherwise it gives away the answer to the challenge.

**Comment by DavidWhaleMEF** [comment] 2017-03-13 20:34
I've managed to break this down to a minimum test case that fails every time. If you press SHAKE on the bottom micro:bit, let the top micro:bit finish scrolling AB then press SHAKE on the bottom micro:bit again once the screen is blank, I get the screen and error as below.

If I just send a non joined string "AB" I never get that error.

I specifically need to join two strings together and then send them via the radio, for the application that I am building.
![screen shot 2017-03-13 at 20 32 58](https://cloud.githubusercontent.com/assets/25079586/23874139/7acc33ea-082c-11e7-9ca7-3d3bcfea0156.png)

**Comment by abchatra** [comment] 2017-03-15 13:36
@DavidWhaleMEF Please share the javascript when you have a short repro. It is way easier to repro with javascript

**Comment by tballmsft** [comment] 2017-04-18 16:13
Yes, please. Always paste in JavaScript code into the github issue, so we can copy/paste.

**Comment by DavidWhaleMEF** [comment] 2017-04-18 18:24
let my_score = 0
let my_label = ""
input.onGesture(Gesture.Shake, () => {
    radio.sendValue(my_label, my_score)
})
radio.onDataPacketReceived(({receivedString: name, receivedNumber: value}) => {
    basic.showString(name)
})
my_label = "A" + "B"
my_score = 0

[shake.txt](https://github.com/Microsoft/pxt/files/930671/shake.txt)

**Comment by DavidWhaleMEF** [comment] 2017-04-18 18:27
FYI, my_label is a simple attempt at application managed addressing in my application. "A" is an application id and 'B' is a message id. The application and message id must be sent together and detected at the receiving end. Any application that sends a message without the 'A' at the start will not affect my running application and the message is dropped. I want to set the "A" part in the on start and add the "B" part based on the action. Remember this is a minimal repro case, so it might not make sense without this description as to why I want the strings separate.

**Comment by tballmsft** [comment] 2017-04-18 20:54
Thanks, David. I'll investigate.

**Comment by tballmsft** [comment] 2017-04-23 01:05
Ah, yes, this is a duplicate of a bug I fixd recently: https://github.com/Microsoft/pxt/issues/1875.

**Closed by tballmsft** 2017-04-23 01:05 UTC
Labels: bug, P1
