### ISSUE TITLE
AnalogPin is restricted to a subset

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#816] opened 2016-11-28 19:11 UTC
Not all pins in PXT support AnalogPin

    declare enum AnalogPin {
        P0 = 7, // MICROBIT_ID_IO_P0
        P1 = 8, // MICROBIT_ID_IO_P1
        P2 = 9, // MICROBIT_ID_IO_P2
        P3 = 10, // MICROBIT_ID_IO_P3
        P4 = 11, // MICROBIT_ID_IO_P4
        P10 = 17, // MICROBIT_ID_IO_P10
    }

But all pins on the target support Analog (DynamicPWM ensures that only 3 work at the same time, but you can use pretty much any pin, apparently).

How could we add more to this list? I tried putting it in a temporary namespace but I get a 'error: any 0x1' when trying to compile.

The Kitronik motor controller board uses P8 for the second motor, and we can't speed control it in PXT.

https://www.kitronik.co.uk/pdf/5620%20Motor%20Driver%20Board%20V1.1-2.pdf

**Comment by abchatra** [comment] 2016-11-28 19:20
@pelikhan Any reason Analog pin is restricted to this subset?

**Comment by pelikhan** [comment] 2016-11-28 19:32
I inferred the list from the MicroBitIO component at https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitIO.cpp#L43

Pin 8 is marked as Digital

    P8 (ID_P8, MICROBIT_PIN_P8, PIN_CAPABILITY_DIGITAL),        //PIN 18

**Comment by abchatra** [comment] 2016-11-28 19:36
This by design then and as hardware supports

**Comment by whaleygeek** [comment] 2016-11-28 19:39
Thanks guys. I'm pretty sure PWM is supported on all pins, but I'll double check with Lancaster and get back to you if anything new surfaces, thanks.

**Comment by pelikhan** [comment] 2016-11-28 23:58
Had a conversation with Joe. Analog out is enabled for all pins (digital), analog in only for analog pins.

**Comment by abchatra** [comment] 2016-11-29 01:42
This is a bug on our side then right?

**Comment by pelikhan** [comment] 2016-11-29 01:49
Yes, working on a fix.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by whaleygeek** [comment] 2016-11-29 10:09
Ok, that's great, thanks so much chaps, excellent!

**Comment by pelikhan** [comment] 2016-11-30 07:25
For now try:
```
pins.analogWritePin(<AnalogPin><any>DigitalPin.P8, 1023)
```

**Comment by whaleygeek** [comment] 2016-12-02 12:07
microbit.org-ticket:298

Customer tried that, but reported that they get an error:

![screen shot 2016-12-02 at 12 04 42](https://cloud.githubusercontent.com/assets/4086785/20833488/e1d4ace2-b887-11e6-81ed-a4fc02dd1e84.png)

**Comment by abchatra** [comment] 2016-12-05 02:33
This works for me. Seems like stale error. There is no property P on DigitalPin

**Comment by whaleygeek** [comment] 2016-12-05 12:49
Customer has re-tried this and says it now compiles fine. Customer also asked that I pass on their thanks to the Microsoft team for the excellent help that you have given in this matter.

**Comment by DFBREB** [comment] 2017-02-05 14:55
I have been told that the PXT team have fixed this issue however from tests I carried out (5/2/17) I do not believe it is fixed.  This is what I have found.

I have tested the following pins on 5/2/17  using https://pxt.microbit.org/beta and an oscilloscope between GND and the relevant pin.

I started by testing known working pins P0, P1, P2 with the script (I will provide) using the long format in Java Script for driving PWM
I then only changed the number of the pin e.g. 0 went to 8 I then recomplied and looked at the 'scope and this is what I found.

Pins  P0, P1, P2 produced a fully controllable and stable PWM signal.

I then selected pins that had no other function e.g did not control LED's etc

Pins P8, P12, P16 produced no signal.  It was steady at GND level.

On odd occasions the editor produced the following message. I did not recompile until the message did not appear.  Incidentally this is the script used for all tests reported with just the number changed.

![image](https://cloud.githubusercontent.com/assets/24857983/22626992/1a2fbf94-ebb1-11e6-99cc-f55baa429f49.png)

The following is the full script to drive pin P1 and P8 from a micro:bit called the receiver rx.  To run this you will also need one or both of the transmitting micro:bit scripts called microbit-Tx-P0M2.hex which drives pin P8 or whichever pin you select.  There is no need to change this script when you change the receivers script.  The second transmitter script is called microbit-TX-P1M1 which drives pin P1

The following are their zip files zipped in Windows 10.

[microbit-Radio-Rx-for-P0-P1long8 newEd.zip](https://github.com/Microsoft/pxt/files/753039/microbit-Radio-Rx-for-P0-P1long8.newEd.zip)

[microbit-Radio-Tx-P0M2.zip](https://github.com/Microsoft/pxt/files/753040/microbit-Radio-Tx-P0M2.zip)

[microbit-Radio-Tx-P1M1.zip](https://github.com/Microsoft/pxt/files/753041/microbit-Radio-Tx-P1M1.zip)

This is the original receiver script which uses the short form of Java Script syntax for output in PWM to pins P0 and P1

[microbit-Radio-Rx-for-P0-P1.zip](https://github.com/Microsoft/pxt/files/753044/microbit-Radio-Rx-for-P0-P1.zip)

Let me know if you have any problems

All the best
David Booth

**Comment by pelikhan** [comment] 2017-02-07 01:35
Related to https://github.com/Microsoft/pxt/issues/611

**Comment by pelikhan** [comment] 2017-02-08 23:34
Handled in #611

**Closed by pelikhan** 2017-02-08 23:34 UTC
Labels: bug, Microbit Foundation, P1
