### ISSUE TITLE
Stray shadow numbers

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/pxt#17] opened 2016-04-22 04:54 UTC
This may be a bug in blockly. In my branch of pxt-sample, I've defined a class as a type that can be assigned to a blockly variable. Using it, I've found a way to create shadow number blocks that are undeletable:
1: Drop a Logic/assignment block
2: Define a block that returns the custom class mentioned above.
3: Drag this block to either argument of the assignment block and attach.
Result: Shadow number wlil pop out and be undeletable from the workspace.
Expected: Shadow number would disappear, or be deletable.

![image](https://cloud.githubusercontent.com/assets/12176807/14732045/7ecf422e-080b-11e6-9e2e-6008fe5af1b5.png)

**Comment by damianburrin** [comment] 2016-06-03 17:36
I can replicate this

**Comment by pelikhan** [comment] 2016-06-03 17:44
Looks like a bug in blockly... Let me see if I can get a smaller repro.

**Comment by pelikhan** [comment] 2016-08-03 23:21
This is a bug in blockly and there's no workaround in sight. When we receive the "changed" event in blockly, we should walk the block list and remove any dangling top level  shadow blocks.

**Comment by riknoll** [comment] 2016-10-05 02:08
Duplicate of #112

**Closed by riknoll** 2016-10-05 02:08 UTC
Labels: Blocks editor, bug, External Bug: Blockly, P3
