### ISSUE TITLE
Blocks categories broken after roundtrip to javascript

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#2876] opened 2017-09-08 15:43 UTC
- open new script https://makecode.microbit.org/beta
- switch to javascri[pt
- click on various categories
- switch back to blocks
- click on categories

![image](https://user-images.githubusercontent.com/4175913/30219717-d11c528a-9471-11e7-80e6-65b0126c8d89.png)

**Comment by microsoftsam** [comment] 2017-09-08 17:56
Dupe of #2723

**Comment by microsoftsam** [comment] 2017-11-15 10:17
This has been fixed. #3132

**Closed by microsoftsam** 2017-11-15 10:17 UTC
Labels: bug, P2
