### ISSUE TITLE
when opening a .blocks file, verify that TS is in sync

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#190] opened 2016-08-03 23:00 UTC
when opening main.blocks, do the same dance as when we convert from TS -> Blocks. Otherwise prompt the user that they should choose which one to pick - same dialog as the failed conversion.

**Comment by tballmsft** [comment] 2016-08-07 08:22
confused about this - I thought that blocks was just a view on TS?

**Comment by pelikhan** [comment] 2016-08-07 16:44
No blocks also contains info that cannot be encoded in the TS: block position, external inputs, disabled blocks etc...

Either the .blocks file is the "master" or the .ts file is "master" depending on what the user is editing.

Sent from Outlook Mobile<https://aka.ms/djubve>

________________________________

**Comment by microsoftsam** [comment] 2016-08-09 06:21
Should we prompt the user or just show the TS? and when the user switches to blocks (they'll be prompted with the dialog to choose.

**Comment by microsoftsam** [comment] 2016-08-09 06:21
Dupe of #141

**Closed** 2016-08-18 22:08 UTC
Labels: Blocks editor, TypeScript editor
