### ISSUE TITLE
Class snippet fail to compile

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#1472] opened 2017-03-01 02:37 UTC
Following snippet fail to compile

```js
class A {
    foo() {

    }
}
class B extends A {
    foo() {
    }
}

let c = new B();
```

**Comment by tballmsft** [comment] 2017-03-16 05:06
traced error to getVtable

**Comment by tballmsft** [comment] 2017-03-16 05:31
Fixed. Test program at https://pxt.microbit.org/09631-25023-49496-07055

**Comment by tballmsft** [comment] 2017-03-16 05:34
Fixed with https://github.com/Microsoft/pxt/commit/3c4926fbf0ccf238a9bf22ef68416a6ca2bb588e

**Comment by tballmsft** [comment] 2017-03-16 07:16
OK. I think I found the bug. Tree shaking is interacting badly with vtable construction.  In your example, you don't call foo.  The following example works:

class A {
    foo() {
        return 1;
    }
}
class B extends A {
    foo() {
        return 2;
    }
}

let b = new A();
let c = new B();
basic.showNumber(b.foo())
basic.showNumber(c.foo())

The problem is that the implementation of foo is removed, but the vtable construction expects to find foo.

**Closed** 2017-03-17 20:52 UTC
Labels: bug, P2, static typescript
