### ISSUE TITLE
Project Open for older .hex files doesn't work 

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#559] opened 2016-10-24 02:10 UTC
- Open Project
- Select an older .hex file (created in codethemicrobit for example). 

![image](https://cloud.githubusercontent.com/assets/6107272/19631682/271b752c-9954-11e6-96fc-8dcc28e5c3fb.png)

**Comment by pelikhan** [comment] 2016-10-25 13:51
Duplicate of #515

**Closed by pelikhan** 2016-10-25 13:51 UTC
Labels: bug
