### ISSUE TITLE
Borders of each package are not in the same class style in Add Package window

### ISSUE THREAD

**Issue by Mofell** [Microsoft/pxt#1966] opened 2017-04-25 06:18 UTC
• Navigate to https://pxt.microbit.org/beta 
• Click Advanced in editor
• Click Add Package

Expect: Border should has same class style
Actual: 
![capture](https://cloud.githubusercontent.com/assets/23447632/25371140/a4df5b1a-29c1-11e7-9db0-210373a232f9.PNG)

**Comment by abchatra** [comment] 2017-04-25 17:23
This is by design, there is a background image for some of the packages. Won't fix from our side.

**Closed by abchatra** 2017-04-25 17:23 UTC
