### ISSUE TITLE
Getting Started light-box effect blacking out screen

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1803] opened 2017-03-30 21:41 UTC
Edge, 1024 x 768, not sure how to repro this... but sometimes tutorial gets into a state where the screen is completely blacked out (instead of the transparent grey).

<img width="510" alt="blackout" src="https://cloud.githubusercontent.com/assets/22108954/24527426/efeb5016-1556-11e7-90d6-23024dc04a0a.PNG">

**Comment by Jaqster** [comment] 2017-03-30 21:43
I think this happens after I download the .hex file onto my microbit

**Comment by abchatra** [comment] 2017-03-30 22:36
Likely dupe of https://github.com/Microsoft/pxt/issues/1804

**Comment by microsoftsam** [comment] 2017-03-30 22:48
Please see if this still repro's on latest.

**Comment by Jaqster** [comment] 2017-04-03 01:12
Still doing this...

**Comment by microsoftsam** [comment] 2017-08-18 16:08
@Jaqster please verify you no longer repro this.

**Closed** 2017-08-18 16:08 UTC
Labels: bug, P2
