### ISSUE TITLE
Script Page enhancements

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1625] opened 2017-03-13 23:47 UTC
Edge, Display: 1024x768
On the Shared script page (i.e. https://pxt.microbit.org/46137-83895-18712-04082):
- when collapsing the simulator, the text overlays on the Zoom buttons
- we can take out the cookie notification popup for the embedded view
<img width="483" alt="text overlay" src="https://cloud.githubusercontent.com/assets/22108954/23879798/a46535f0-080c-11e7-8321-387d43820c42.PNG">

**Comment by microsoftsam** [comment] 2017-03-14 05:41
Dupe of #1625

**Closed** 2018-05-15 22:31 UTC
Labels: P3, bug
