### ISSUE TITLE
The focus of mouse was not on the correct element

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2920] opened 2017-09-12 09:18 UTC
Repro steps:
• Navigate to https://makecode.microbit.org/beta on FireFox
• Drag block "show leds" and put it under the block "on button A pressed"
• Change the all element values to 1 in the forth line of the block "show leds"
• Move the mouse to the elements in the third line

Expected result:
The focus was on the elements in the third line 
Actual result:
The focus was still on the elements in the forth line when the mouse was on the bottom of the element in the third line, and when clicked the mouse, the value of element in the forth line was changed.

Additional information:
The focus was on the element in the third line if the value of element in the forth line didn't change to 1

![mouse](https://user-images.githubusercontent.com/11880996/30317828-e712b3c6-97dd-11e7-9e0e-8561f6a673ec.gif)

**Comment by microsoftsam** [comment] 2017-09-20 09:03
Dupe of #2721 ?

**Comment by yanlxu** [comment] 2018-01-17 08:38
@samelhusseini , this bug is not same with #2721, about this bug, when we pointed to the Led with mouse(pointed to the bottom of the Led), the focus was not on the Led which we pointed to, the focus was on the Led below the Led which we pointed to

**Comment by Helen09** [comment] 2018-03-13 02:41
Still repro on firefox(58.0.2)

**Closed** 2018-05-15 22:30 UTC
Labels: P3, UI, bug, cti team
