### ISSUE TITLE
Odd simulator LED scaling on Firefox

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt#3197] opened 2017-10-10 12:12 UTC
Seen on Firefox 56.0, the following code will cause the second Icon to be displayed with about half the scaling:
```
let item: game.LedSprite = null
basic.showIcon(IconNames.Happy)
item = game.createSprite(2, 2)
basic.showIcon(IconNames.Sad)
```
![scaling](https://user-images.githubusercontent.com/29712657/31385837-8c07b00e-adbc-11e7-96f0-677eb1d70384.gif)

Not really sure what's the trigger, if it's something specific to the sprite block or something else.

MakeCode versions:
makecode.microbit.org version: 0.13.27
Microsoft MakeCode version: 0.14.1
C++ runtime version: v2.0.0-rc11

**Comment by abchatra** [comment] 2017-10-10 16:34
Likely duplicate of https://github.com/Microsoft/pxt/issues/2700

**Closed by abchatra** 2017-10-10 16:34 UTC
Labels: bug
