### ISSUE TITLE
Debugger feature

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt#4729] opened 2018-09-25 20:50 UTC
![debugger](https://user-images.githubusercontent.com/4175913/46043293-801c4d80-c0cc-11e8-93df-b45ad0ec61ed.png)

## Description

The debugger allows to execute code step by step, i.e. block by block or statement by statement. When the code is paused, one can inspect the values of variables. A debugger toolbar appears that allow to pause, resume the execution or add a breakpoint block.

## How to enable it?

Press the bug button to enter debugging mode.

![image](https://user-images.githubusercontent.com/4175913/46043364-acd06500-c0cc-11e8-8eae-fd2710ea53a7.png)

Once in debugging mode, you will see the debugger toolbar accross the coding workspace (we have a bug currently where it gets masked by the "Experiments" notification)

![image](https://user-images.githubusercontent.com/4175913/46155466-35b1e280-c22c-11e8-80aa-24274057ae09.png)

If you cannot see that button and you editor supports this experiment, go to **About**, then click **Experiments** and **Debugger**. If you cannot see this card, your editor does not support yet this feature.

## Feedback

Do you use this feature? Is there something you'd like to change? Did you encounter issues? Please drop a comment on this issue to send us your feedback.

**Comment by abchatra** [comment] 2018-09-25 21:01
I don't understand this bug

**Comment by pelikhan** [comment] 2018-09-25 21:05
Place holder for experiment docs

**Comment by abchatra** [comment] 2018-09-27 14:46
This doesn't work in Chrome 69
![image](https://user-images.githubusercontent.com/6107272/46154149-65abb680-c229-11e8-995b-add33c5533db.png)

**Comment by abchatra** [comment] 2018-09-27 14:46
I can't see any of the toolbar

**Comment by pelikhan** [comment] 2018-09-27 15:07
The "Experiments" notification bar pushes the menu over that toolbar.

**Comment by whaleygeek** [comment] 2019-01-04 18:19
How do we see variable values in javascript mode? Are there any docs on how to use this feature?

**Comment by abchatra** [comment] 2019-01-04 18:34
Feature is not yet fully implemented. Only blocks is implemented. This is work in progress.

**Comment by rei-vilo** [comment] 2019-02-12 11:56
The debugger seems to work only on the board shown on the left pane of MakeCode, but not on the real board.

![capture 2019-02-12 a 12 54 15](https://user-images.githubusercontent.com/951776/52633648-5fab2f00-2ec5-11e9-890d-be9bb1db4c03.png)

On the example above, the board shown on the left pane of MakeCode stops at each breakpoints. But the real board continues to blink the LED even if the program is stopped at one breakpoint.

**Comment by abchatra** [comment] 2019-02-12 18:24
@rei-vilo this debugger feature is only for simulator today. Hopefully someday in future we will support hardware debugging through webusb.

**Comment by jwunderl** [comment] 2019-04-10 16:52
On Microbit, breakpoints are not working when in ``on start`` unless they occur after a ``pause``: https://github.com/Microsoft/pxt-microbit/issues/1995

**Comment by tguneysu** [comment] 2019-04-26 19:38
Hi Guys,
Just found out about the Debugger experimental feature and tried it.
I was having a problem with Sprite properties and wanted to use it to examine it.
My problem was that after deleting a Sprite, its properties were still returning values. As such I was unable to determine its deletion status.
When I used the Debugger, I noticed a property _ENABLED that was not shown in the Sprite properties blocks. So I decided to check it out via Debugger to see if I could display it.

Here is what happened:
- I placed my normal code in the A+B button pressed block onto the coding area and then switcched over to JS mode and replaced it with a display for the _ENABLED property. 
- When I tried switching back to the BLOCKS mode, I got an error saying this property did not exist. Mind you that it was displaying in the Debugger Object expanded view.
- So I corrected my code to display object_X instead, in order to get rid of the error and be able to go back to the Blocks mode.
- When I switched over, I realized that all my original code of the A+B button block was gone, replaced with the latest version of displaying Object_X.

Now, I am not sure if this is because of the presence of the Debugger in my code or not! However, I have been pushing code aside from blocks and testing new code in this fashion for a while without any problems

Just wanted to report in case it is a bug / problem.

I will do some more testing and provide further info.

**Comment by abchatra** [comment] 2019-04-29 16:48
@tguneysu can you share your program?

**Comment by mkchingHK** [comment] 2019-05-04 03:34
Very happy to see 'Debugger feature' and have to say 'Thank you'. It can help the kids to understand the real programming. I would like to suggest the followings:
1)  The 'breakpoint' is called 'debugger' in javascript. Do you think it would be to use 'breakpoint'?
2)  Is it possible to have the call stack?

MK

**Comment by microbit-mark** [comment] 2019-05-14 10:57
From micro:bit support: 22157

"Noticed today that debugger display of program variables are at fault as such:

It will display the variable values only if it is NOT the last entry in an event block, such as "onStart".
The last entry in such a block does NOT get displayed.
Put another command block behind the last variable, and it will display.

Simply remove the "show Icon" block and aString variable value will not be shown in debugger vars. Add it and it will show.

The first gif shows the variables being set and the second one skips the last variable
 
![Pzepvmb3BPluNisRlWhJ_ZNeMdm5yyNSFg](https://user-images.githubusercontent.com/31242877/57692684-4a1de080-763f-11e9-9ed4-50627138bb0a.gif)
![QySOKKGsJC64CV75Hn96F2KIcRt5smHfPg](https://user-images.githubusercontent.com/31242877/57692687-4be7a400-763f-11e9-92e0-659606dc6de5.gif)


This behaviour is the same in the current Editor, BETA Editor, and the standalone Win MakeCode program.

**Comment by abchatra** [comment] 2019-05-14 18:13
@microbit-mark above is as intended. The block is not executed yet when it hits the breakpoint.

**Comment by whaleygeek** [comment] 2019-05-14 19:07
@microbit-mark for clarification, until a set var=value block is executed, the variable does not exist. Variables in MakeCode (javascript) are dynamically created on first write (unlike C which defines the memory space for variables at compile time).

If the user has been used to using a compiled language like C, this may be confusing them.

**Comment by abchatra** [comment] 2019-05-14 21:00
@whaleygeek yes, perfect explanation.

**Comment by riknoll** [comment] 2020-04-14 17:13
@abchatra not sure what the action item is on this issue

**Comment by abchatra** [comment] 2020-04-14 17:14
To see if we address all the feedback here. I went through it once and looks like we have addressed all. Closing.

**Closed by abchatra** 2020-04-14 17:14 UTC
Labels: debugger

**Comment by pelikhan** [comment] 2020-04-14 17:16
Are you removing it from the experiment list? It is still linked there.

**Comment by abchatra** [comment] 2020-04-14 17:18
Can you point where in the code?

**Comment by riknoll** [comment] 2020-04-14 17:46
@abchatra https://github.com/microsoft/pxt/blob/master/pxteditor/experiments.ts#L58
