### ISSUE TITLE
Problem Importing NeoPixel Library into PXT

### ISSUE THREAD

**Issue by nevilh** [Microsoft/pxt#923] opened 2016-12-13 19:26 UTC
There seems to be some problems loading and disabling libraries in PXT for the micro:bit

When I tried loading the NeoPixel library it says it is loading the library and I don't get any error message but no extra NeoPixel menu options are provided. I then tried to load one of the other libraries (the devices library) and I get the prompt message

"Packages Bluetooth and NeoPixels cannot be used together"

so it seem to think the NeoPixel library is loaded but if I select "Remove Bluetooth" I just get this same prompt message returning repeatedly. I can only get rid of the prompt message by selecting "Remove NeoPixel"

If I then close the browser window and open a new one, it opens with the Bluetooth Menu Options available. If I then try and add the Radio library I get the prompt message

"Packages Bluetooth and Radio cannot be used together"

which once again won't allow me to "Remove Bluetooth" but will allow me to "Remove Radio"

It looks like there may be a problem removing the Bluetooth Library and a problem adding the NeoPixels Library. If you have a moment could you take a look?

FYI I'm using Windows 7 with Internet Explorer 11.

Regards,

Nevil

**Comment by abchatra** [comment] 2016-12-13 21:39
I do think this is a duplicate of https://github.com/Microsoft/pxt/issues/558. I will keep it open till we investigate

**Comment by pelikhan** [comment] 2016-12-20 17:27
@nevilh do you have the script source?

**Comment by pelikhan** [comment] 2016-12-22 19:19
This issue is fixed in beta. Please reopen if still a problem.

**Closed by pelikhan** 2016-12-22 19:19 UTC
Labels: Browser Compat, bug, P1
