### ISSUE TITLE
User feedback: Javascript isn't appealing to click

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#885] opened 2016-12-07 22:29 UTC
Hour of Code, 07/12/16, Darrington HS

The JavaScript button isn't highlighted enough. From my observation, no kid clicked on it. Maybe it should show something else, like: "Code", or maybe it needs to be a different color. For many, Javascript was a little foreign.

Let's discuss / experiment.

**Comment by jaustin** [comment] 2016-12-07 23:46
@pelikhan has been looking at showing the code alongside the blocks and I think this might be a great way to entice people into editing it too.

**Comment by microsoftsam** [comment] 2016-12-08 01:16
That's a good idea. 
Another thing we could do is make it more of a toggle switch. So instead of being a button, it could be something like this: 
![screen shot 2016-12-07 at 5 15 45 pm](https://cloud.githubusercontent.com/assets/16690124/20993697/d3d2726a-bca0-11e6-9b30-23c739b22bf2.png)

**Comment by pelikhan** [comment] 2016-12-08 07:44
If the name "javascript" is foreign to them, then the text inside the javascript editor is going to be foreign as well. We need to make the JS editor friendlier before trying to bring users to it more aggressively.

**Comment by EdNutting** [comment] 2016-12-09 03:21
@microsoftsam Code instead of JS will be confusing because kids see the blocks as code. A Code button would send mixed signals / send some children off track. 

@jaustin / @pelikhan  Code alongside blocks with the tabs for accessing blocks and the simulator? Never going to fit on the average screen in the schools I work with. The editor is already cramped as it is. 
1280px wide is about as big as it gets still. 

I like the toggle button idea, assuming the view toggles without losing all the blocks layout, positioning, zoom, etc

**Comment by pelikhan** [comment] 2016-12-09 03:35
@EdNutting  not a fan at all of the side by side blocks/javascript.

**Comment by jaustin** [comment] 2016-12-09 17:30
When described by the researchers we talk to, the point of the side-by-side stuff is to invite people towards understanding text based coding as a follow on from blocks, not a jump.  I think the idea is that it It teaches them about code as they go...

The common thing we hear is that kids have to go back and re-learn text-based coding after moving on from blocks, and many people never do, and teachers are scared of it too. The idea of seeing "this block maps to that text" might be able to help there. I agree, there are big UI complexities.

@EdNutting and @pelikhan what do you think about the 'slider' in the bottom of the CodeKingdoms editor?
![image](https://cloud.githubusercontent.com/assets/147113/21058190/c93df244-be34-11e6-9921-c2d5a28a0b59.png)
-->
![image](https://cloud.githubusercontent.com/assets/147113/21058200/d6fe78ea-be34-11e6-9c7d-5e514bd19971.png)

play here: https://www.microbit.co.uk/app/#create:tomwku

**Comment by pelikhan** [comment] 2016-12-09 18:10
The problem is that teachers want "scratch"-like blocks with a canvas where you can drop blocks anywhere. No sliders from there.

In PXT, blocks and js are built on two different editor stack, sliders highly unlikely to happen.

**Comment by EdNutting** [comment] 2016-12-09 19:26
I agree with the idea of moving people along by allowing block editing while they see the effect on the text based code. 

The reality sadly though is that screen sizes and cheap hardware setup means computers used in classrooms either aren't big enough or aren't fast enough to make it work properly. 

The slider on Code Kingdoms is good. But as @pelikhan says, that might be hard to reproduce for the PXT editor. 

Is there a way to do a "highlight box" or something, that when you select a block, it shows you the JS just for that block? (without its contents). That clear separation of code and direct link from one block to specific lines of code would solve the transfer problem and solve the problem of teachers/students being overwhelmed by the mass of JS produced by lots of blocks.

**Comment by EdNutting** [comment] 2016-12-09 19:28
(Without its contents meaning the loops and conditional blocks just shown "while (xyz) {...} where xyz is the actual condition from the code but '...' is literally "...". 

Statements / expressions could then show their action in bold and sub-blocks in non-bold)

**Comment by pelikhan** [comment] 2016-12-09 19:54
> Is there a way to do a "highlight box" or something, that when you select a block, it shows you the JS just for that block? 

We could render javascript in the codecard in the bottom right.

**Comment by EdNutting** [comment] 2016-12-09 20:06
Yep, with a switch to turn that on/off that could work quite well.

**Comment by jaustin** [comment] 2016-12-09 20:10
That would be nice per block but I would love not to lose sight of the desire to see the whole program change as a block goes in/ moves etc. 

--
Please excuse brevity and typos, this was sent from a phone

**Comment by pelikhan** [comment] 2016-12-09 20:12
> I would love not to lose sight of the desire to see the whole program change as a block goes in/ moves etc.

As soon as you have more than a few blocks, I don't see how a kid could correlate changes in blocks and changes in a second pane of containing dozens of lines of JavaScript.

**Comment by jaustin** [comment] 2016-12-09 20:18
--
Please excuse brevity and typos, this was sent from a phone

> On 9 Dec 2016, at 20:13, Peli de Halleux <notifications@github.com> wrote:
> 
> I would love not to lose sight of the desire to see the whole program change as a block goes in/ moves etc.
> 
> As soon as you have more than a few blocks, I don't see how a kid could correlate changes in blocks and changes in a second pane of containing dozens of lines of JavaScript.
> 

What about highlighting/colouring the currently selected block and/or recently changed blocks?

**Comment by OwenBrotherwood** [comment] 2016-12-09 21:52
Proposal: 
- simple item in the advanced that has word Javascript with different colors for each letter that performs the function of the _really_ boring Javascript menu item
- removal of Block Menu item when in Blocks anyway
- removal of the _really_ boring Javascript menu item when in Blocks (see rainbow Javascript proposal)
- what ever you fancy to get back to Blocks from Javascript
- complement with Javascript exposure whilst in Blocks: eg. expose in help card for block

Background:
- Screen area: useless Blocks and Javascript menu items
- Those who will go forward will go forward, and be attracted by Advanced

**Comment by OwenBrotherwood** [comment] 2016-12-10 06:01
In general,
Please remember that all forms of automatic popup eg help or whatever, have a context under self learning.
However, if a teacher is showing a pupil "something", all forms of popup will distract the eye of the pupil from the what the teacher may be trying to show.

Self-learning contra being taught mode switch as a concept.

**Comment by OwenBrotherwood** [comment] 2016-12-10 19:49
![image](https://cloud.githubusercontent.com/assets/866122/21075751/1e441a12-bf1a-11e6-8027-cc3f96b96caa.png)

**Comment by OwenBrotherwood** [comment] 2016-12-10 19:55
![image](https://cloud.githubusercontent.com/assets/866122/21075780/d515c808-bf1a-11e6-95e1-9fb4223feb63.png)
Except I forgot the hamburger menu beside the stop button

And I like in these times of python v's javascript that our old favorit programming language is back: basic.forever !

**Comment by OwenBrotherwood** [comment] 2016-12-13 22:15
Screen shot of 1024x768 with the new toolbox for the javascript editor.
The work done to obtain a road for going from blocks to javascript with recognisable elements is great.
However, losing space on the right of the screen and javascript can be written with short lines, but tabulation for clear indentation gives hell in the long run.
The race is between getting out of beta and schools moving to higher resolution screens with the pupils progress from going from blocks to javascript (and the world ending).

![image](https://cloud.githubusercontent.com/assets/866122/21161708/0a29c758-c18a-11e6-883a-e6969053bf56.png)

**Comment by pelikhan** [comment] 2016-12-22 19:22
Removal of code card https://github.com/Microsoft/pxt/pull/987

**Comment by abchatra** [comment] 2017-04-20 01:15
We have moved Javascript\Blocks as tabbed interface grouped together. Fixed from our end.

**Closed by abchatra** 2017-04-20 01:15 UTC
Labels: enhancement, user feedback
