### ISSUE TITLE
generalize lambdas

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#133] opened 2016-07-20 23:09 UTC
to allow multiple parameters and return value.

**Comment by mmoskal** [comment] 2016-07-21 08:12
This isn't very useful without generics #122

**Comment by thomasdenney** [comment] 2016-07-21 14:35
The error message for `lambda functions cannot yet return values` shows in the calling location, but not on the `return` statement in the lambda, e.g. the error message shows on the second line for the following:

```typescript
let f = () => { return 0 }
basic.showNumber(f())
```

**Comment by mmoskal** [comment] 2016-08-18 09:49
This is duplicate of #39

**Closed by mmoskal** 2016-08-18 09:49 UTC
Labels: enhancement
