### ISSUE TITLE
Microbit events block when entering conditional while loop

### ISSUE THREAD

**Issue by lesander** [Microsoft/pxt#3445] opened 2017-11-09 13:55 UTC
Basically, after entering the `doOverflow` while loop, the MicroBit is no longer able to handle any (input) events. The emulator on https://makecode.microbit.org however does handle this async behaviour correctly.

Is this expected behaviour? If not, the emulator should be adapted to ensure the same behaviour as a real MicroBit (?).

```js
// [...]

input.onButtonPressed(Button.B, () => {
    doOverflow = false
    imageHappy()
})
input.onButtonPressed(Button.A, () => {
    doOverflow = true
    imageEvil()
})

radio.setGroup(1)
imageHappy()

basic.forever(() => {
    while (doOverflow) {
        radio.sendString("Radio Jamming <3")
    }
})
```

**Comment by pelikhan** [comment] 2017-11-09 17:01
Make sure to add a short pause in your tight loop to allow other events to run.

```
 while (doOverflow) {
        radio.sendString("Radio Jamming <3")
        basic.pause(1)
    }
````

**Comment by abchatra** [comment] 2017-11-09 18:13
Thread are non-preemptive in Micro:bit runtime (DAL). You need pause to transfer the control to on button event. This is by design.

**Comment by lesander** [comment] 2017-11-09 18:40
Thank you @abchatra and @pelikhan for your explanations. It is good to learn that this is intended behaviour on the MicroBit's end.

The issue that remains is that the browser-side emulator on [makecode.microbit.org](https://makecode.microbit.org) does not behave the same as the MicroBit. The emulator is able to listen for inputs during the while loop, while the MicroBit is unable to multi-task because of the non-preemptive thread behaviour.

**Comment by abchatra** [comment] 2017-11-09 18:45
That is a good feedback. It is bit hard in the browser to emulate pure non-preemptive scheduling. We will look into that issue.

**Comment by abchatra** [comment] 2018-07-03 23:02
I am closing this bug. We don't have a good solution in the current design and will look into this in future.

**Closed by abchatra** 2018-07-03 23:02 UTC
Labels: P2, bug, simulator
