### ISSUE TITLE
Invalid type inference with arrays

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#2349] opened 2017-06-25 02:59 UTC
Try this program. The inference engine tries to force players to be a string, it should be a number[].

https://makecode.microbit.org/_1TKKu575rbJd

**Comment by tballmsft** [comment] 2017-06-25 22:48
another reason to use TypeScript type inference rather than rolling our own.

**Comment by riknoll** [comment] 2017-06-29 23:26
Duplicate of https://github.com/Microsoft/pxt/issues/2349

**Closed by riknoll** 2017-06-29 23:26 UTC
Labels: blocks <==> typescript, bug

**Comment by riknoll** [comment] 2017-06-29 23:30
@tballmsft the issue is that we can't generate typescript without first doing the type inference. We need to declare types for the variables in the generated code.
