### ISSUE TITLE
Servo write not working properly on real micro:bit

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#1399] opened 2017-02-24 21:07 UTC
microbit.org-ticket: 1096

We are developing some servo based product, but the attached hex file does not work as expected. Pressing button A on a real micro:bit causes the pin attached to button B to change as well as the expected change, and vice versa.

![screen shot 2017-02-24 at 21 06 16](https://cloud.githubusercontent.com/assets/25079586/23320969/1f506338-fad5-11e6-8529-d940bcf2cc04.png)

[servo.problem.hex.zip](https://github.com/Microsoft/pxt/files/800476/servo.problem.hex.zip)

**Comment by abchatra** [comment] 2017-02-25 01:10
Works in simulator, haven't tested the microbit yet
```js
basic.forever(() => {
    while (input.buttonIsPressed(Button.A)) {
        pins.servoWritePin(AnalogPin.P1, 180)
    }
    pins.servoWritePin(AnalogPin.P1, 90)
    while (input.buttonIsPressed(Button.B)) {
        pins.servoWritePin(AnalogPin.P2, 0)
    }
    pins.servoWritePin(AnalogPin.P2, 90)
})
```

**Comment by pelikhan** [comment] 2017-02-25 12:37
Please provide schematics of the wiring for this project.

**Comment by DaveAtKitronik** [comment] 2017-02-27 11:16
The system is wired as per the automatically drawn schematic in the PXT editor.
Both servos power and ground to the battery pack. micro:bit also powered from battery pack.
Servo 1 signal pin to P1 and Servo 2 signal pin to P2.
![capture](https://cloud.githubusercontent.com/assets/25896029/23359213/177f5902-fcdd-11e6-82cc-de293169f83a.PNG)

Looking on an oscilloscope the issue appears to be that pushing button A lengthens the P1 pulse, as expected, but also lengthens P2 from 1.5mS to 1.66mS 
Pushing button B shortens P2 pulse to 560uS, but lengthens P1 pulse to 1.66mS.

I will try to grab some scope screenshots.

**Comment by DaveAtKitronik** [comment] 2017-02-27 11:48
I have also noticed that the repeat frequency drops from 50Hz when no button is pressed to ~45Hz when either button is pressed.
Scope screenshots attached.
![scope - no buttons pressed](https://cloud.githubusercontent.com/assets/25896029/23360317/9a2099e8-fce2-11e6-8eec-b6e77b3cb1f7.PNG)
![scope button b pressed](https://cloud.githubusercontent.com/assets/25896029/23360319/9a20a4d8-fce2-11e6-86e9-2c7092e3e026.PNG)
![scope - button a pressed](https://cloud.githubusercontent.com/assets/25896029/23360318/9a20b0e0-fce2-11e6-8594-ba606925d455.PNG)

Dave

**Comment by DaveAtKitronik** [comment] 2017-02-27 12:09
Just checked in blocks and the periods are steady. However the first channel defined as servo write appears to be inverted.

**Comment by pelikhan** [comment] 2017-02-27 14:49
We are merely using features of the c++ DAL. It would be good to rewrite a C++ only version of this bug. I suspect the issue is lower in the stack.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by finneyj** [comment] 2017-03-20 23:49
@DaveAtKitronik  @pelikhan 

I wonder if this is related to the busy loop - the constant updating of servo value in a tight loop... I'll investigate.

**Comment by DaveAtKitronik** [comment] 2017-03-21 08:02
@finneyj If you need any help just ask
Dave

**Comment by finneyj** [comment] 2017-03-21 21:11
Thanks @DaveAtKitronik. Might have some C for you to test in a bit. :-)

**Comment by finneyj** [comment] 2017-03-22 12:14
@DaveAtKitronik 

OK... Struggling to reproduce this in C.  I just compiled and tested the following code on microbit-dal#rc8, and can't see any change in period of either channel, irrespective of the state of the buttons. My scope is constant at 49.977Hz...

```

**Comment by finneyj** [comment] 2017-03-22 12:23
@DaveAtKitronik @DavidWhaleMEF  @pelikhan @abchatra 

Just reproduced the Blocks code too, from a clean project on the live pxt.microbit.org. 

I can't repro this bug on my scope either. Trace there is also constant at 49.98Hz... 

Can anyone else reproduce this?

![image](https://cloud.githubusercontent.com/assets/11539567/24197594/26419c00-0efa-11e7-9834-06c4af69a360.png)

**Comment by DaveAtKitronik** [comment] 2017-03-22 12:28
@finneyj  does the original hex file I attached produce the fault for you?

**Comment by finneyj** [comment] 2017-03-22 12:38
@DaveAtKitronik 

It does indeed. I get a really nasty 5Hz jitter as you described. I don't see it on either of the builds above though... attaching my HEX files here in case you'd like to verify.

[microbit-pwm-glitch-test.zip](https://github.com/Microsoft/pxt/files/861388/microbit-pwm-glitch-test.zip)

**Comment by DaveAtKitronik** [comment] 2017-03-22 12:40
@finneyj  Does the hex wrap up all the lower level bits and bobs? If so could a fix to the PWM mean this is no longer an issue?
Will try your hex.

**Comment by finneyj** [comment] 2017-03-22 12:41
@DaveAtKitronik 

Yes, HEX includes which version of microbit-dal the code was compiled against. Is it possible your HEX file was generated before the latest version of PXT was made live?

**Comment by DaveAtKitronik** [comment] 2017-03-22 12:50
@finneyj Yes.
 I don't know when the latest version went live, but the hex was uploaded here about the time I was testing the PWM mods. 
Your PXT .hex is steady at 49.98
It does suggest that this has been fixed since reporting.

**Comment by finneyj** [comment] 2017-03-22 12:59
@DaveAtKitronik  Judging by the data this issue was raised, your HEX is will be running the old PWM driver.

The new driver went live with microbit-dal#rc8 and that was only tagged 21 days ago. This issue pre-dates that by 5 days. This is starting look like an issue that's already been resolved.

**Comment by DaveAtKitronik** [comment] 2017-03-22 13:03
@finneyj  I'm happy with that resolution. I guess there is no way to tell what dal is baked into the hex?

**Comment by finneyj** [comment] 2017-03-22 19:47
@DaveAtKitronik  The version number is recorded in the runtime, but only really accessible through a function call - so not so visible by static inspection of the HEX file. If Bluetooth is enabled then it's also visible through the Device Information service on there. 

There might be a way to get the PXT version and backtrack though. @pelikhan ?

**Comment by DavidWhaleMEF** [comment] 2017-05-02 22:19
@finneyj @DaveAtKitronik can we close this issue now?

**Comment by DaveAtKitronik** [comment] 2017-05-03 07:13
@DavidWhaleMEF  I think so.  I haven't seen it since.

**Closed** 2017-05-03 08:44 UTC
Labels: bug, P2
