### ISSUE TITLE
The simulator couldn't display when open the example project "Radio Dashboard"

### ISSUE THREAD

**Issue by yanlxu** [Microsoft/pxt#2860] opened 2017-09-05 07:55 UTC
Repro steps:
• Navigate to https://makecode.microbit.org/beta 
• Click "Projects" in the Menu bar
• Click the "Examples"
• Select the project "Radio Dashboard" to open

Expected result:
There are no alerts in the content panel and the simulator could display
Actual result:
There are alerts in the content panel and the simulator couldn't display 

![projects-radio-dashboard](https://user-images.githubusercontent.com/11880996/30050875-8834e5a8-9252-11e7-811c-1bf1cccf90c6.gif)

**Comment by abchatra** [comment] 2017-09-06 16:38
Another decompiler issue. @riknoll 
The program is correct in typescript, but we automatically decompile to blocks (which is incorrect but an authoring issue). Decompiler results in an incorrect program.

**Comment by abchatra** [comment] 2017-09-06 16:40
I think it is array decompiler issue which converts to an empty array which loses type inference. Convert it to grey blocks

**Comment by riknoll** [comment] 2017-09-06 22:50
Pretty sure the issue is the radio packet messing everything up (look at the grey block, it's invalid code). I fixed this in master a while back, I'll cherry pick it over

**Comment by riknoll** [comment] 2017-09-08 16:42
Fixed by https://github.com/Microsoft/pxt/pull/2878

**Closed** 2017-09-08 16:47 UTC
Labels: bug, P1
