### ISSUE TITLE
forever executes code before onStart has completed

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1324] opened 2017-02-09 15:57 UTC
microbit.org-ticket: 889

In the PXT beta beta editor I encounter the problem that the code in on start is not fully executed before the forever loop is started. This isn't intuitive for me when I compare this to arduino for example. In my case it caused an action in the foreverloop which shouldn't be possible based on the variable initialized in onstart. I currently fixed it with a boolean initialized as false and set to true at the end of the on start procedure, in the forever loop an additional if statement triggered on initialized. 

While typing this I realize that the onstart isn't present in the javascript editor.

**Comment by abchatra** [comment] 2017-02-09 18:02
Please share the code. Unless there is a pause somewhere in onstart which will transfer the control to forever, this shouldn't be the case.

**Comment by pelikhan** [comment] 2017-02-09 18:48
Most likely, they are calling an async function in main (like basic.showString) which gives the opportunity to forever to start running.

**Comment by DavidWhaleMEF** [comment] 2017-02-09 21:47
Sure, I am waiting for the customer to share some code at the moment, will upload it once I have it.

I think your analysis is good though, and I'll look out for this when the user sends the code through to us.

**Comment by pelikhan** [comment] 2017-02-09 21:51
Forever start a fiber which runs  a loop with 20ms wait so it will start on the first "yield" it gets.

**Comment by abchatra** [comment] 2017-04-18 17:45
Closing the issue as there is no code from the customer

**Closed by abchatra** 2017-04-18 17:45 UTC
Labels: needs additional information

**Comment by DavidWhaleMEF** [comment] 2017-04-18 18:17
Thanks @abchatra - I polled the customer for sample code, but unfortunately they did not provide any.

I have however written a small k-base article detailing the cause/workaround if someone else has a similar issue.

https://support.microbit.org/solution/articles/19000053084-forever-runs-before-onstart-finishes

Clearly this is normal operation, but knowledge of how the underlying scheduling occurs is required to understand this fully.

**Comment by nielsswinkels** [comment] 2017-09-20 13:10
Is there a way to force the forever loop to wait for the onstart to be done, even though there is a wait in the onstart? It is very unintuitive.

Example code that contains a wait in the onstart:
https://makecode.microbit.org/_6aaJEueisWD5

**Comment by nielsswinkels** [comment] 2017-09-20 13:27
Related thread with more discussion: https://github.com/Microsoft/pxt/issues/2385

**Comment by pelikhan** [comment] 2017-09-20 14:19
The next deployment of the editor will enforce this behavior.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment] 2017-09-20 15:06
This is fixed. Fix will be available in next release
