### ISSUE TITLE
"Download Screenshot" doesn't work on IE

### ISSUE THREAD

**Issue by charmian01** [Microsoft/pxt#1852] opened 2017-04-06 02:28 UTC
**Repro step:**

- Navigate to https://pxt.microbit.org/beta on IE
- Right click on Blocks editor->Download Screenshot

 **Expect result:**
"Download Screenshot" can capture images
**Actual result:**
There is not responding

**Comment by tballmsft** [comment] 2017-04-06 22:06
cannot repro. Please give more detailed instructions.

**Comment by microsoftsam** [comment] 2017-04-07 00:06
I believe this is a known issue. Right click in Blockly -> Download screenshot doesn't work in IE.
This is because there isn't SVG to PNG support in IE. We should not show that option in IE.

**Comment by microsoftsam** [comment] 2017-04-07 00:07
Dupe of #557

**Closed by microsoftsam** 2017-04-07 00:07 UTC
Labels: needs additional information
