### ISSUE TITLE
Firefox: ShowLED block highlights incorrect LED sometimes

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#3557] opened 2017-12-04 17:30 UTC
Firefox 57.0.1 (64-bit) on macOS 10.12.6

The video below shows this best. It seems that when the mouse cursor moves below the bottom half of one 'LED' the 'LED' below is selected. Clicking will toggle the state of the wrong LED, but clicking again will change the state of the correct one. 
![led mouse alignment](https://user-images.githubusercontent.com/147113/33566604-6b3ca596-d918-11e7-8ab7-853faf1d2dac.gif)
Reproduceable in live and /beta
I can't make it happen in Chrome, nor in Safari.

**Comment by microsoftsam** [comment] 2017-12-06 05:22
Dupe of https://github.com/Microsoft/pxt/issues/2721

**Closed by microsoftsam** 2017-12-06 05:22 UTC
